// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try { require("dotenv/config"); } catch { }
import { defineConfig } from "prisma/config";

// Fallback for Docker environment
const databaseUrl = process.env["DATABASE_URL"] || "file:/app/data/tablo.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
